(function(){"use strict";
let token="",lastId="",lastUpdate=0,controller=null,running=false,runId=0;
const el=id=>document.getElementById(id), text=(id,value)=>el(id).textContent=value==null?"未知":String(value);
if(location.hash==="#fixture")el("demo_notice").hidden=false;
function setConnected(yes){const e=el("connection");e.textContent=yes?"已连接":"未连接";e.classList.toggle("ok",yes);if(!yes&&lastUpdate){text("online","未连接（旧快照）");text("freshness","连接断开");text("frequency_freshness","连接断开")}}
function bool(v){return v==null?"未知":v?"是":"否"}
function age(value){if(value==null)return null;const t=Date.parse(value);if(!Number.isFinite(t))return null;return Math.max(0,Math.round((Date.now()-t)/1000))+" 秒前"}
function render(s){if(!s||typeof s!=="object")return;setConnected(true);lastUpdate=Date.now();const stale=s.freshness==="stale";const rigStale=s.rig_fresh===false;const rigState=s.rig_fresh===true?"实际频率新鲜":rigStale?"实际频率陈旧":"实际频率未知";text("last_update","流更新时间："+(s.generated_at||"未知"));text("web_server_state",s.web_server_state);text("application_name",s.application_name);text("mode_band",[s.mode,s.band].filter(Boolean).join(" / ")||"未知");text("instance_id",s.instance_id);text("online",s.online==null?null:(s.online?(stale?"在线（数据陈旧）":"在线"):"离线"));text("frequency",s.frequency==null?"未取得实际频率":(Number(s.frequency)/1000000).toFixed(6)+" MHz");text("freshness",stale?"陈旧":s.freshness==="fresh"?"新鲜":s.freshness);text("frequency_freshness",rigState);text("last_status_update",s.last_status_update);text("last_decode_update",s.last_decode_update);text("decode_age",age(s.last_decode_update));text("dx_call",s.dx_call);text("dx_grid",s.dx_grid);text("report",s.report);text("df",(s.rx_df==null?"未知":s.rx_df)+" / "+(s.tx_df==null?"未知":s.tx_df));text("tx_mode",s.tx_mode);text("tx_enabled",bool(s.tx_enabled));text("transmitting",bool(s.transmitting));text("decoding",bool(s.decoding));text("tx_first",bool(s.tx_first));text("watchdog_timeout",bool(s.watchdog_timeout));text("cq_qso",[s.cq_state,s.qso_stage].filter(Boolean).join(" / ")||"未知");text("auto_sequence_state",s.auto_sequence_state);text("current_tx_text",s.current_tx_text);const rows=Array.isArray(s.recent_decodes)?s.recent_decodes:[];text("decode_count",rows.length);const box=el("decodes");box.replaceChildren();rows.slice().reverse().forEach(d=>{const row=document.createElement("div");row.className="decode";[[d.time,""],[d.snr,""],[d.delta_frequency,""],[d.mode,""],[d.callsign,""],[d.grid,""],[d.fresh?"新鲜":"陈旧",""],[d.is_new?"新":"旧",""],[d.message,"text"]].forEach(([v,c])=>{const x=document.createElement(c?"b":"span");x.className=c;x.textContent=v==null?"未知":String(v);row.appendChild(x)});box.appendChild(row)})}
function auth(){return token?{"Authorization":"Bearer "+token}:{} }
function timedRead(reader,run){let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error("watchdog")),15000)});return Promise.race([reader.read(),timeout]).finally(()=>clearTimeout(timer)).then(v=>{if(run!==runId)throw new Error("superseded");return v})}
async function stream(run){while(running&&run===runId){const local=new AbortController();controller=local;try{const headers=auth();if(lastId)headers["Last-Event-ID"]=lastId;const r=await fetch("/api/v1/events",{headers,cache:"no-store",signal:local.signal});if(run!==runId)throw new Error("superseded");if(r.status===401){el("auth_error").textContent="令牌无效";running=false;setConnected(false);break}if(!r.ok||!r.body)throw new Error("HTTP "+r.status);setConnected(true);const reader=r.body.getReader(),decoder=new TextDecoder();let buf="";while(running&&run===runId){const n=await timedRead(reader,run);if(n.done)throw new Error("stream ended");buf+=decoder.decode(n.value,{stream:true});const parts=buf.split("\n\n");buf=parts.pop();for(const part of parts){const id=part.split("\n").find(x=>x.startsWith("id: "));if(id)lastId=id.slice(4);const event=(part.split("\n").find(x=>x.startsWith("event: "))||"").slice(7);if(event!=="snapshot")continue;const line=part.split("\n").find(x=>x.startsWith("data: "));if(line){try{render(JSON.parse(line.slice(6)))}catch(_){}}}}}catch(_){if(run===runId){setConnected(false);if(running)await new Promise(resolve=>setTimeout(resolve,1000))}}finally{local.abort();if(run===runId)controller=null}}}
el("connect_button").addEventListener("click",()=>{runId++;running=false;if(controller)controller.abort();token=el("token_input").value;el("auth_error").textContent="";running=true;stream(runId)});
setInterval(()=>{if(lastUpdate&&Date.now()-lastUpdate>15000)setConnected(false)},1000);
})();
